project:
  type: website
  output-dir: "docs"

website:

  title: "Welcome"
  navbar:
    left: 
      - text: "Home"
        file: zindex_main.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Education"
      - file: qducation.qmd
      - text: "Workshops"
        file: workshops.qmd
      
    right:
      - icon: github
        href: https://github.com/borison365
      - icon: twitter
        href: https://twitter.com/tamegye_boris
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

