project:
  type: website
  output-dir: "docs"

website:


  title: "About"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Projects"
        file: project.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/borison365
      - icon: twitter
        href: https://twitter.com/tamegye_boris
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

